[bastion]
bastion ansible_host=10.0.20.1

[web]
web ansible_host=10.0.30.4

[db]
db ansible_host=10.0.30.5

[zabbix]
zabbix ansible_host=10.0.30.6

# Hotes supervises par un agent Zabbix (config commune dans group_vars/agents.yml)
[agents:children]
web
db

[all:vars]
ansible_user=admin-tmpl
ansible_python_interpreter=/usr/bin/python3