---
all:
  children:

    # ── Nœuds Proxmox ─────────────────────────────────────────────────────────
    proxmox:
      hosts:
        prx1:
          ansible_host: 10.0.10.1
          proxmox_node_id: 1
          ceph_public_ip: 10.0.101.1
          ceph_private_ip: 10.0.102.1
          ceph_osd: true
          ceph_bond_members: [enic1, enic2]

        prx2:
          ansible_host: 10.0.10.2
          proxmox_node_id: 2
          ceph_public_ip: 10.0.101.2
          ceph_private_ip: null
          ceph_osd: false
          ceph_nic: nic2   # SFP→RJ45, accès VLAN 101 direct

        prx3:
          ansible_host: 10.0.10.3
          proxmox_node_id: 3
          ceph_public_ip: 10.0.101.3
          ceph_private_ip: 10.0.102.3
          ceph_osd: true
          ceph_bond_members: [enic1, enic2]

    # ── Sous-groupes Ceph ──────────────────────────────────────────────────────
    ceph_osd:
      hosts:
        prx1:
        prx3:

    ceph_mon:
      hosts:
        prx1:
        prx2:
        prx3:

    ceph_mgr:
      hosts:
        prx1:
        prx2:

    # ── Switch Arista ─────────────────────────────────────────────────────────
    arista:
      hosts:
        ynov-sw-lab:
          ansible_host: 10.0.10.253
          ansible_network_os: arista.eos.eos
          ansible_connection: ansible.netcommon.network_cli
          ansible_user: admin
          ansible_password: "{{ vault_arista_password }}"
          ansible_become: true
          ansible_become_method: enable

    # ── PC Windows (NAT WAN) ──────────────────────────────────────────────────
    windows:
      hosts:
        pc-wan:
          ansible_host: 10.0.99.1
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_user: "{{ vault_windows_user }}"
          ansible_password: "{{ vault_windows_password }}"
